### ISSUE TITLE
Make linkdrop landing page according to figma template

### ISSUE THREAD

**Issue by AngelBlock** [NEAR-labs/labs-kanban#35]
## 🤼‍♂️   Reviewer

@Kisgus @eclipseeer @AngelBlock 

## 🔗   Work doc(s) / inspirational links
- https://www.figma.com/file/3n7Eameef6WuFI21lgtey2/Near-Linkdrop?node-id=0%3A1

**Comment by Kisgus** [comment]
Added more updates in #36 as well, Stas / designer is working on updating the figma file
