### ISSUE TITLE
Update "vesting scheme" wording in lockup.tech 

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#37]
## 📋   **Anything to add?**

**Change "Vesting Scheme" to "Select lockup type"**

<img width="265" alt="Screenshot 2021-11-08 at 17 27 11" src="https://user-images.githubusercontent.com/18598519/140780125-60b8ef72-6127-44f9-83fd-dc4d0003a477.png">

**Change drop-down to**
- linear release
- 1-year cliff

<img width="308" alt="Screenshot 2021-11-08 at 17 27 13" src="https://user-images.githubusercontent.com/18598519/140780133-65b16383-24e7-44a4-b48f-d906e0974858.png">

**Comment by AngelBlock** [comment]
done
