### ISSUE TITLE
Add tests to the Linkdrop v2 contracts

### ISSUE THREAD

**Issue by Kisgus** [NEAR-labs/labs-kanban#4]
## 📋   Anything to add?

Title

## 🎉   Subtasks

- [x] Unit tests
- [x] Integration tests
- [x] Simulation tests

## 🤼‍♂️   Reviewer

@AngelBlock 

## 🔗   Work doc(s) / inspirational links
Documentation on NEAR-specific Rust tests 
- https://learn.figment.io/tutorials/write-and-deploy-a-smart-contract-on-near#testing-the-contract
- https://docs.near.org/docs/develop/contracts/rust/testing-rust-contracts

**Comment by AngelBlock** [comment]
Examples of the tests can be found in core contracts repository https://github.com/near/core-contracts/blob/master/lockup/tests/spec.rs
